
name: 'Create a new release'
on:
  push:
    tags:
      - '*'
jobs:
    build_release:
      uses: Sensirion/sht43-demoboard-ble-firmware/.github/workflows/check_and_build.yml@main
      secrets: inherit
    create_release:
      runs-on: ubuntu-22.04
      permissions:
        contents: write
      needs: build_release
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Get build artifacts
          uses: actions/download-artifact@v3
          with:
            name: sht43-ble-firmware
            path: ${{github.workspace}}/artifacts
        - name: Create new release
          id: create_release
          uses: ncipollo/release-action@v1
          with:
            name: "Release ${{github.ref_name}}"
            artifacts: |
              ${{github.workspace}}/artifacts/release/*.hex,
              ${{github.workspace}}/artifacts/release/*.bin,
              ${{github.workspace}}/artifacts/release/*.elf
            bodyFile: ${{github.workspace}}/CHANGELOG.md
            tag: ${{github.ref_name}}
